### ISSUE TITLE
Stock app icons not applying automatically

### ISSUE THREAD

**Issue by Jimmyb1126** [dkanada/frost#100]
Since I upgraded from LineageOS 14.1 (Nougat) to 15.1 (Oreo), the icons of certain system apps aren't being changed automatically with Frost. It mostly likely has something to do with the new Oreo circle icons.
This is an issue with launchers that don't allow you to manually change icons such as KISS. I've tried it with other launchers such as Trebuchet and still have the issue with the same apps. I haven't encountered this with every system app. Most of them, such as Settings and Messaging, can be applied like usual with the icon pack.

The apps that I've encountered this issue with are the following:
AudioFX (org.lineageos.audiofx)
Camera (org.lineageos.snap)
Music (org.lineageos.eleven)
Phone (com.android.dialer)

Unfortunately, Turtl kept crashing for me (only when these certain icons were selected), so I was not able to collect the icon files.
I've also noticed that the icon for the F-Droid app "Red Moon" does not apply automatically, but is visible in the icons list. This may just be because the F-Droid release hasn't been updated yet, I'm not sure.

**Comment by dkanada** [comment]
I am working on some updates for this app to add in the request functionality from turtl, and at that point I will also fix the issue we are both having with the crash. My guess is that Red Moon has been updated but this icon pack does not have the updated activity name, hence the broken icon. That can be fixed as soon as I get requests working again. The other issue you mentioned with system apps and the new adaptable icons sounds like it requires a bit of digging, so I will get to that one last. Thanks for the information!

**Comment by dkanada** [comment]
Turtl should be working fine now, please let me know if you still have issues. As for the icon requests, I added a "copy" option to Turtl that works perfectly fine here since all of these apps already have icons in the icon pack.

**Comment by fredddii** [comment]
I am in the same boat. Those four stock applications are not receiving icons.

The Turtl result:

```
<!-- AudioFX -->
<item component="ComponentInfo{org.lineageos.audiofx/org.lineageos.audiofx.activity.ActivityMusic}" drawable="audiofx"/>
<!-- Camera -->
<item component="ComponentInfo{org.lineageos.snap/com.android.camera.CameraLauncher}" drawable="camera"/>
<!-- Music -->
<item component="ComponentInfo{org.lineageos.eleven/org.lineageos.eleven.ui.activities.HomeActivity}" drawable="music"/>
<!-- Phone -->
<item component="ComponentInfo{com.android.dialer/com.android.dialer.app.DialtactsActivity}" drawable="phone"/>
```

**Comment by dkanada** [comment]
Just added them to the appfilter, they should be working in the next update, thanks.
