### ISSUE TITLE
Simple Apps now use icon color in activity name

### ISSUE THREAD

**Issue by swedneck** [dkanada/frost#101]
Is there a better fix for this than just adding every variation to the appfilter.xml?

**Comment by dkanada** [comment]
That really sucks, but as far as I know there isn't support for wildcards or anything in the file. I would change it but the spec itself was decided by a single launcher like ten years ago so doing it a different way wouldn't work on any current launchers. All it does is parse the entire file and match an activity name to a drawable resource in the xml file, so unfortunately the only way is to manually add all the activity names.

**Comment by swedneck** [comment]
I'm gonna try to slog through this at some point (i have nothing better to do anyways), hopefully the colors are the same for all apps.
