### ISSUE TITLE
Turtl not working - need help to send an icon request

### ISSUE THREAD

**Issue by Leroux47** [dkanada/frost#108]
Hello everyone,

I want to send a icon request, but I can't get Turtl running on my phone : it stops everytime I want to send an icon request... So how can I send a request without Turtl ? Does someone have a functional version of the app ?

Thanks in advance for your responses.

**Comment by dkanada** [comment]
Yeah, something in a new version of android broke the request app. I will look into it and see if I can fix it.

**Comment by dkanada** [comment]
Just fixed the app and pushed the update to F-Droid, feel free to open a new issue with the requested icons!
