### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by conrad-heimbold** [dkanada/frost#11]
[Turtle (edited to make png file names shorter)](https://github.com/dkanada/ICEcons/files/1050623/20170604_072142-edited.zip)

**Comment by Donnnno** [comment]
Here's a list with the icons , the strikethrough apps are in the icon pack:

- ~~AnySoftKeyboard~~
- APKUpdater
- Auto Updater for Chromium
- Drinks
- ~~Gadgetbridge~~
- ~~LibreOffice Viewer~~
- ~~LibreTorrent~~
- Material Player
- Metrodroid
- MinMinGuard
- ~~Notepad~~
- ~~oandbackup~~
- Offline Calendar
- Orgzly
- ~~PPSSPP~~
- ~~SkyTube~~
- ~~Steam~~
- ~~Street­Complete~~
- Survival Manual
- TV KILL
- ~~Wire~~
- XDA Labs
- Xposed Installer
- XPrivacy

**Comment by Donnnno** [comment]
@dkanada This issue can be closed too, all the remaining icons were added in the latest update. :)
