### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by fredddii** [dkanada/frost#113]
See screenshot. Using LineageOS 15.1 and even some basic applications are no longer working.

Can not use the regular icon request submission tool so this has to do for now.

![frost-icons](https://user-images.githubusercontent.com/15217150/46164775-287a0f80-c28f-11e8-9ffe-a5447229b071.png)

**Comment by dkanada** [comment]
I just updated Turtl to fix the crash so it should work fine now. Also, there is now an option to copy the required fields to the clipboard which would work perfectly here since the lineage apps should already be included in the icon pack.
