### ISSUE TITLE
'Red Moon' icon not displayed

### ISSUE THREAD

**Issue by crishaddad** [dkanada/frost#122]
The 'Red Moon' App should have an icon; it exists in the pack, but is not applied for some reason (using Openlauncher).

I've had a look at the appfilter.xml and drawable.xml and they seem to be correct as far as I can see, so maybe someone else who knows a bit more about what's going on under the hood can take a look(?).

[Demo of issue on openlauncher, and screenshots of app info, hosted on Imgur](https://imgur.com/a/Bi6MqyX).

Cheers.

**Comment by dkanada** [comment]
Looks like the issue was a change to the appfilter, it will be working in the next update.
