### ISSUE TITLE
Outdated logo for BlaBlaCar

### ISSUE THREAD

**Issue by ohemelaar** [dkanada/frost#141]
Hello again,
I see that the logo in the icon for BlaBlaCar is outdated, the brand changed it a few months ago I think. But their new app has a different package/activity name. I'm planning on updating this icon in a future PR, should we ditch the old icon in the meantime?

**Comment by dkanada** [comment]
We can leave the old icon for now, there are actually a few apps in this state, another one being Emerald Launcher on F-Droid. An old icon is better than no icon most of the time.

**Comment by ohemelaar** [comment]
I wanted to put my updated icon alongside the old one, so someone can chose which one to chose. However, is the appfilter.xml file meant to have several possible drawables for the same activity ? I tried the following:
```xml
<item component="ComponentInfo{com.comuto/com.comuto.proxy.ProxyActivity}" drawable="blablacar"/>
<item component="ComponentInfo{com.comuto/com.comuto.proxy.ProxyActivity}" drawable="blabla_circle"/>
```
But then when choosing an icon it only "finds" the last one (I'm using Nova Launcher).

**Comment by dkanada** [comment]
If you made an updated icon we can just use that one. You are correct, you can't use two different icons for like that unfortunately.
