### ISSUE TITLE
Icons missing for below apps

### ISSUE THREAD

**Issue by sultanahamer** [dkanada/frost#142]
Some FLOSS app icons are missing on my device.

**Diode**

Also for the below apps, icon is same and is looking like a divided by symbol(kind of odd)
**SimpleFileManager
SimpleGallery**

**Comment by dkanada** [comment]
The SimpleFile apps should be fixed in the next update. I will work on Diode if I find the time, thanks for reporting it.

**Comment by sultanahamer** [comment]
@dkanada thanks for the quick response. Waiting for the next release

**Comment by dkanada** [comment]
@sultanahamer just wanted to confirm this was fixed since the latest update on F-Droid?

**Comment by sultanahamer** [comment]
Yes, got them anf are looking great.

-------- Original Message --------
On 17 Feb 2019, 12:34 PM, dkanada wrote:

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by dkanada** [comment]
Good to hear!
