### ISSUE TITLE
(How) are custom app shortcuts supported?

### ISSUE THREAD

**Issue by ialokim** [dkanada/frost#148]
I wanted to add support for [Transportr](/grote/Transportr) to this project, but I've noticed there are pinned [Shortcuts](https://developer.android.com/guide/topics/ui/shortcuts/) being used, which use different icons. Is there a way to replace them for an Android theme, too, and how should I do it?

Just for your interest, the shortcuts are defined [here](https://github.com/grote/Transportr/blob/master/app/src/debug/res/xml/shortcuts.xml).

**Comment by dkanada** [comment]
There isn't really a standard way to do that unfortunately, the method most launchers support only works for the app icons themselves.

**Comment by dkanada** [comment]
Transportr should already be in the icon pack though, if you send me the component name I can update it to work for your version.

**Comment by ialokim** [comment]
@dkanada That's kind of sad, but thanks for your reply!

**Comment by ialokim** [comment]
That's what Turtle gives me for Transportr. Would be great if you can include it!


<item component="ComponentInfo{de.grobox.liberario/de.grobox.transportr.map.MapActivity}" drawable="transportr"/>
