### ISSUE TITLE
Riot.im icon not applying

### ISSUE THREAD

**Issue by tekofu** [dkanada/frost#169]
Hi,

I have a few icons not in the pack already but I see there's a riot.im icon in frost but it isn't applying in my launcher (KISS Launcher). I'm not sure if this is an issue with frost or my launcher but any help would be appreciated.

Here's the output from turtl

<item component="ComponentInfo{im.vector.alpha/im.vector.activity.VectorLauncherActivity}" drawable="riot.im"/>

Thanks in advance

**Comment by dkanada** [comment]
This should be fixed in the latest version, let me know if it isn't and I'll reopen the issue.
