### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by kazukyakayashi** [dkanada/frost#188]
Hi :)

1List
DNSfilter
Exodus Privacy
Firefox Preview
Free Mobile Netstat
Lockwise
Mysplash
OUI.sncf
Podom=C3=A8tre (https://f-droid.org/fr/packages/de.j4velin.pedometer/)
RiotX
Send
Sumatora
Timber

[20190928_035104.zip](https://github.com/dkanada/frost/files/3665533/20190928_035104.zip)

**Comment by Donnnno** [comment]
Added every icon except for Sumatora

**Comment by kazukyakayashi** [comment]
Thank you for your amazing work.
