### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Herbstfreud** [dkanada/frost#191]
Hello,

there are some F-Droid Apps which have no Frost Icons yet. Would you mind to add them in a future release?

- Blokada
- OpenTodoList
- PhoneTrack
- APKGrabber
- DuckduckGo Browser
- OctoDroid
- Screencam

Thank you!

**Comment by Donnnno** [comment]
What are the package and activity name (see https://github.com/dkanada/frost#icon-requests)?

(There are already icons for Blokada & DuckDuckGo)

**Comment by Herbstfreud** [comment]
Hello,
I've installed Turtl and tried to extract the ZIP file but I didn't find the file in my phone then...

Does this help?


<item component="ComponentInfo{de.apkgrabber/de.apkgrabber.activity.MainActivity_}" drawable="apkgrabber"/>

<item component="ComponentInfo{org.blokada.alarm/core.PanelActivity}" drawable="blokada"/>

<item component="ComponentInfo{com.duckduckgo.mobile.android/com.duckduckgo.app.launch.LaunchActivity}" drawable="duckduckgo"/>

<item component="ComponentInfo{com.gh4a/com.gh4a.activities.Github4AndroidActivity}" drawable="octodroid"/>

<item component="ComponentInfo{net.rpdev.opentodolist/org.qtproject.qt5.android.bindings.QtActivity}" drawable="opentodolist"/>

<item component="ComponentInfo{net.eneiluj.nextcloud.phonetrack/net.eneiluj.nextcloud.phonetrack.android.activity.LogjobsListViewActivity}" drawable="phonetrack"/>

<item component="ComponentInfo{com.orpheusdroid.screenrecorder/com.orpheusdroid.screenrecorder.ui.MainActivity}" drawable="screencam"/>

**Comment by xmiul** [comment]
Go to your phone's settings and give Turtl access to your internal storage under the permissions menu, then try again and you'll get the zip.

**Comment by Herbstfreud** [comment]
Thank you. ;)

[20191016_060259.zip](https://github.com/dkanada/frost/files/3740881/20191016_060259.zip)

**Comment by Donnnno** [comment]
Hi, I've created/updated the icons :) you can find it here #194
