### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by xmiul** [dkanada/frost#193]
[20191015_010319.zip](https://github.com/dkanada/frost/files/3727565/20191015_010319.zip)

**Comment by Donnnno** [comment]
Hi, I've added the icons, you can view them here: #200

**Comment by xmiul** [comment]
> 
> 
> Hi, I've added the icons, you can view them here: #200

Thanks and good work, Donnnno. I like them. Can you please make a new one for this zip file? It's just an icon for the Aurora Services app, a background installing extension for Aurora Droid & Aurora Store. 
[20191023_015335.zip](https://github.com/dkanada/frost/files/3764003/20191023_015335.zip)

**Comment by Donnnno** [comment]
Sure, I'll look into it :-)

**Comment by Donnnno** [comment]
Something like this, I'll add it when I've fixed my repo :)
![afbeelding](https://user-images.githubusercontent.com/31142286/67426101-abc47c80-f5d9-11e9-8d43-7acbb63c0895.png)

**Comment by xmiul** [comment]
> 
> 
> Something like this, I'll add it when I've fixed my repo :)

Nice, thank you.

**Comment by xmiul** [comment]
I decided to reopen the request because the Aurora Services icon wasn't added in the latest Frost update (1.6.2.32). I can confirm that the other icons were added.
