### ISSUE TITLE
Fruitradar Icon not rendered correctly

### ISSUE THREAD

**Issue by TheLie0** [dkanada/frost#199]
First of all, thanks for adding my icons so fast!

The fruitradar icon in the drawable folders seems to be a plain white square though.

**Comment by DanielMowitz** [comment]
Whoops wrong account

**Comment by dkanada** [comment]
I've seen this before, for some reason my scripts don't properly render any svg files that use the mask property. If you remove that and then fix the icon in another pull request it should work. I can also fix it eventually when I have time.
