### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by zsinskri** [dkanada/frost#2]
[Turtl](https://github.com/dkanada/ICEcons/files/1004670/20170516_035701.zip)

**Comment by dkanada** [comment]
I have finished a few of these so far, I will add a new release soon after some more additions.

**Comment by Donnnno** [comment]
Here's a list with the icons , the strikethrough apps are in the icon pack.

- ~~AntennaPod~~
- ~~Audio Recorder~~
- ~~BetterBatteryStats~~
- ~~Birthday Adapter~~
- ~~Calculator~~
- Calendar Import-Export
- ~~Clock+~~
- ~~Dialer2~~
- ~~DiskUsage~~
- ~~Downloads~~
- ~~Draw~~
- Earmouse

- Easy Dice
- Export Contacts
- Fate Sheet
- ~~Feeder~~
- FFUpdater
- ~~Gallery~~
- Headphone detector for Vanilla Music
- ~~ICSdroid~~
- Jamendo
- ~~K9 Material (unofficial)~~
- ~~KISS launcher~~
- ~~LabCoat~~
- ~~LibreOffice Viewer~~
- Liquid Wars OS
- ~~Magisk Manager~~
- Micopi+
- Minetest
- ~~Mozilla Stumbler~~
- My App List
- Padland
- ~~People~~
- ~~Phone~~
- ~~Practice Hub~~
- Quick Dice Roller
- QuickDic
- ~~Riot~~
- ~~SatStat~~
- ~~Silence~~
- ~~Slide~~
- Son of Hunky Punk
- ~~Street­Complete~~
- Terminal Emulator
- ~~Transportr~~
- Type and Speak
- USB Mountr
- ~~Vanilla Music~~
- WiFiKeyShare
- ~~Yalp Store~~
