### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by tuch96** [dkanada/frost#210]
Hi!

First of all thanks a lot for this amazing icon pack on f-droid!!

It is possible to add the missing icons? I have add the zip file from the turtle app.

Thank you!!!

[20191028_091437.zip](https://github.com/dkanada/frost/files/3790481/20191028_091437.zip)

**Comment by nonnominandus** [comment]
I will create the ones that are missing.

**Comment by nonnominandus** [comment]
![preview](https://user-images.githubusercontent.com/25853274/67894632-374d8880-fb59-11e9-98fc-8de81c694f48.png)
I created them and will include them include them in my next pull request.

**Comment by tuch96** [comment]
Wow... fantastic!! Thank you so much!!
