### ISSUE TITLE
Icon request.

### ISSUE THREAD

**Issue by marcdw1289** [dkanada/frost#214]
AsteroidOS Sync
Item component="ComponentInfo{org.asteroidos.sync/org.asteroidos.sync.PermissionsActivity}" drawable="asteroidossync"

Battery Charge Limit
item component="ComponentInfo{com.slash.batterychargelimit/com.slash.batterychargelimit.activities.MainActivity}" drawable="batterychargelimit"

CPU Stats
item component="ComponentInfo{jp.takke.cpustats/jp.takke.cpustats.PreviewActivity}" drawable="cpustats"

GApps Browser
item component="ComponentInfo{com.tobykurien.google_news/com.tobykurien.google_news.GoogleNewsActivity}" drawable="gappsbrowser"

Joplin
item component="ComponentInfo{net.cozic.joplin/net.cozic.joplin.MainActivity}" drawable="joplin"

MatLog Libre
item component="ComponentInfo{com.pluscubed.matloglibre/com.pluscubed.logcat.ui.LogcatActivity}" drawable="matloglibre"

MyAndroidTools
item component="ComponentInfo{cn.wq.myandroidtools/cn.wq.myandroidtoolspro.MainActivity}" drawable="myandroidtools"

The latter also has MainDarkActivity when using dark/night theme.

[20191031_014541.zip](https://github.com/dkanada/frost/files/3792969/20191031_014541.zip)

**Comment by h-bruch** [comment]
Added CPU Stats and BatteryChargeLimit in https://github.com/dkanada/frost/pull/218

**Comment by h-bruch** [comment]
Can be closed. All of them added in https://github.com/dkanada/frost/pull/218
