### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by OVERPWREDCATSCIENCE** [dkanada/frost#215]
[20191103_034811.zip](https://github.com/dkanada/frost/files/3802116/20191103_034811.zip)

**Comment by h-bruch** [comment]
Except for Herecomesthebus (https://play.google.com/store/apps/details?id=com.synovia.herecomesthebus&hl=en_US) and Slide (https://f-droid.org/en/packages/me.ccrama.redditslide/) the icons were added in https://github.com/dkanada/frost/pull/218
