### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [dkanada/frost#216]
Ref: https://f-droid.org/wiki/page/com.dkanada.icecons/lastbuild_32

**Comment by dkanada** [comment]
I thought I caught all those, my apologies. Will retagging the release work fine? I'd rather not skip version numbers.

**Comment by licaon-kter** [comment]
Yes, retag after fixup. Thanks

**Comment by dkanada** [comment]
@licaon-kter I might have done the update wrong, is there a new problem with the build? There was another issue but I fixed that as well.

**Comment by licaon-kter** [comment]
Another contributor disabled the build https://gitlab.com/fdroid/fdroiddata/commit/147777202c74fc2ada72796e23919eaa5fdd77c3


I'll reenable it asap
