### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by xmiul** [dkanada/frost#217]
Hi, it's just an icon for the Open Contacts app. It's stock icon is pretty generic in my opinion, so maybe it would be better to not use it as a reference, since it would look like the AOSP dialer icon from the Frost pack.

Thanks in advance.

[20191104_111027.zip](https://github.com/dkanada/frost/files/3807357/20191104_111027.zip)

**Comment by h-bruch** [comment]
How about using the contacts icon from Frost? It looks like this:
https://github.com/dkanada/frost/blob/master/icons/contacts.svg

**Comment by xmiul** [comment]
> How about using the contacts icon from Frost? It looks like this:
> https://github.com/dkanada/frost/blob/master/icons/contacts.svg

Yes, I think it would be way better to make it based on that Frost icon, but with some modification.

**Comment by h-bruch** [comment]
Since the app saves contacts in a safe, maybe like this? If you have something in mind, please make a suggestion.

![opencontacts svg](https://user-images.githubusercontent.com/52801243/68467810-26ff7280-0217-11ea-8339-870b423350ce.png)

**Comment by xmiul** [comment]
> 
> 
> Since the app saves contacts in a safe, maybe like this? If you have something in mind, please make a suggestion.
> 
> ![opencontacts svg](https://user-images.githubusercontent.com/52801243/68467810-26ff7280-0217-11ea-8339-870b423350ce.png)

Yes, I think the shield makes sense considering the main function of the app. Thanks a lot h-bruch.
