### ISSUE TITLE
Aurora Services icon not being applied in the latest Frost update

### ISSUE THREAD

**Issue by xmiul** [dkanada/frost#221]
This icon is new and it can be seen in the icons list (Frost v1.6.2.32), but it isn't applied in the launcher.
![Screenshot_20191115-214341_KISS_launcher](https://user-images.githubusercontent.com/56573899/68987693-851cee80-07f1-11ea-9772-64d179d705bb.png)

**Comment by Donnnno** [comment]
Can you provide the activity name of the app?

**Comment by xmiul** [comment]
> Can you provide the activity name of the app?

Here is the zip file made with Turtl
[20191023_015335.zip](https://github.com/dkanada/frost/files/3855202/20191023_015335.zip)
