### ISSUE TITLE
App icon not visible with light themes

### ISSUE THREAD

**Issue by Donnnno** [dkanada/frost#236]
I noticed a while ago that the app icon isn't visible in F-droid and Aurora droid when you have the light theme enabled. As you can see here:

![Screenshot_20191213-125026_Aurora_Droid](https://user-images.githubusercontent.com/31142286/70798597-a698d800-1da7-11ea-9eb1-ee963c2cad66.png)

So I tought about creating one that's both visible on light & dark themes like for example one of these two icons:

![Artboard 5](https://user-images.githubusercontent.com/31142286/70798840-540beb80-1da8-11ea-856b-423265791a3a.jpg)

So let me know what you think about this idea :-)

**Comment by dkanada** [comment]
Maybe we could use a similar image as the blurred header image (or the same one) for the background of the icon. I think internally the icon pack should still use the same pure white icon since it will only show when applied in a launcher.

**Comment by Donnnno** [comment]
> Maybe we could use a similar image as the blurred header image (or the same one) for the background of the icon.

![Artboard 6](https://user-images.githubusercontent.com/31142286/70934485-4d96a180-203e-11ea-8aec-f9853b1982f6.jpg)
Maybe something like this then? (created with the existing blurry image).

> I think internally the icon pack should still use the same pure white icon

True, it would be weird if it was not.

**Comment by dkanada** [comment]
I love the first one, you can add the svg file to other and I'll update the icon for the next release.

**Comment by Donnnno** [comment]
Thanks :) I'll add it to a pull request, I don't know if it's an issue but I used a clipping mask for the image.

**Comment by Donnnno** [comment]
Hey, happy new year! Sorry for the long wait but do you know another way to make images round other than clipping masks?

**Comment by dkanada** [comment]
I will try and figure out why the masks are getting deleted in my scripts. Your new icon pull request doesn't have the blurred image though, it seems the image referenced in the svg file isn't embedded there?

**Comment by Donnnno** [comment]
> 
> 
> it seems the image referenced in the svg file isn't embedded there?
Yea I saw it thanks, it's embedded now.
