### ISSUE TITLE
Icon for KeePass DX not applied

### ISSUE THREAD

**Issue by hexaholic** [dkanada/frost#244]
I believe the settings for the KeePass DX app need to be updated. The default icon is used instead of the Frost version.

Here is the xml output from Turtl:

```<!-- KeePass DX -->
<item component="ComponentInfo{com.kunzisoft.keepass.libre/com.kunzisoft.keepass.activities.FileDatabaseSelectActivity}" drawable="keepassdx"/>```

**Comment by nonnominandus** [comment]
I added this new name in my pending merge request, so it should be solved pretty soon.

If you want the icon to be applied now you could try if your launcher supports hand set icons (most do, including Nova).
