### ISSUE TITLE
Icon for (google) contacts not applying

### ISSUE THREAD

**Issue by mihawk90** [dkanada/frost#246]
Just installed this pack yesterday from F-Droid because I saw it in the Update-Stream, and it seems no icon is applied for the Stock Android Contacts App `com.google.android.contacts`.

I found this weird because it should be rather widespread, so I checked your `appfilter.xml`. I may or may not have found the culprit in that the activity seems to be defined multiple times:

[Line 465](https://github.com/dkanada/frost/blame/6094e597661e5b7a3563f35bf7ad94c466bd0a98/app/src/main/res/xml/appfilter.xml#L465)
[Line 471](https://github.com/dkanada/frost/blame/6094e597661e5b7a3563f35bf7ad94c466bd0a98/app/src/main/res/xml/appfilter.xml#L471)
And probably most importantly [Line 928](https://github.com/dkanada/frost/blame/6094e597661e5b7a3563f35bf7ad94c466bd0a98/app/src/main/res/xml/appfilter.xml#L928)

While 465 and 471 define the same icon `contacts` (I assume `drawable` refers to the filename?), 928  defines `people` instead, probably overwriting the previous definitions.

Unfortunately I don't know how to test for this.

**Comment by nonnominandus** [comment]
For me the Google contacts did also not work. It uses the same activity name as you posed. I solved it by manually setting the icon (can be done by most launchers). I think the multiple definitions are at best redundant and maybe even cause this issue as you suggested, but I do not know enough of how this icon pack works to know for sure or test.
