### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by kazukyakayashi** [dkanada/frost#254]
Hello 🙂 

Frost 1.7.1 with KissLauncher on OnePlus 6T Android 10

## List

- aurora store (*icon not applied*)
- cityzen (*f-droid*)
- firefox preview (*icon not applied*)
- ghost (*f-droid*)
- gitnext (*f-droid*)
- mpdroid (*f-droid*)
- music (*icon not applied*)
- oko LightMeter
- otter
- rocket chat (*f-droid*)
- session
- snapspeed (*icon not applied*)
- movim (*f-droid*)

[20200221_114947.zip](https://github.com/dkanada/frost/files/4235661/20200221_114947.zip)

**Comment by nonnominandus** [comment]
Added extra activity name:
* Firefox preview
* Music added
* Snapseed

New icons for:
* Cityzen
* Ghost
* Gitnex
* Mpdroid
* Oko lightmeter
* Otter
* Rocket chat
* Session

![preview9](https://user-images.githubusercontent.com/25853274/82200790-c0fb5280-98ff-11ea-96d7-7ef0cb0ee754.png)

Problems:
* Aurora store name was already in place
* Movim is missing from the zip file so I was not able to create an icon for it.

I will include the new icons in my pull request. If you have any suggestions or comments feel free to post them!
