### ISSUE TITLE
Missing icons in last PNG generation

### ISSUE THREAD

**Issue by mihawk90** [dkanada/frost#257]
Hey there,

when I first saw the commit I wasn't sure if I just missed something, but after the update hit the F-Droid store I can tell I didn't :D 

The "generate new icons" commit a9d0866497a855874c7d373ea457840abcd54031 didn't add any of the icons from #250 (possibly more, I didn't check), and 334074b0c993839062d245559be3f3970c545811 added them (and more) to the XMLs, which should have already been in there for the release I guess?

In the Icon Overview inside the app the icons are also missing, they are just blank spots. And of course they're also not selectable (or automatically applied for that matter).

**Comment by dkanada** [comment]
For some reason one of the scripts I use doesn't work with masks. Removing those from the affected files should work, or fixing the script. I may have some time soon.

**Comment by mihawk90** [comment]
Mh, maybe I'm overlooking it but I don't see any masks in the files (and I can't remember using any myself, maybe just inkscape being weird). Pretty much at the end of doing everything I was converting all the objects to paths, so that should be OK.

On the bright side as a side-note: Google Contacts are fixed :ok_hand:

**Comment by dkanada** [comment]
It was my mistake, the next release should fix this!
