### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by tuch96** [dkanada/frost#259]
Hi all, after the last app update of my qr-code scanner, the icon is showing only the original version. Maybe you can fixed?!

Frost Version 1.7.2 with Kiss Launcher.

Thanks a lot!!

Kind  regards
[20200311_030205.zip](https://github.com/dkanada/frost/files/4318722/20200311_030205.zip)

**Comment by nonnominandus** [comment]
I added the new activity name to the names list. So the frost icon should be reaplied when my pull request is merged and a new version of frost is distributed.

**Comment by nonnominandus** [comment]
@dkana or @tuch96 As the new activity name is added I guess this issue can be closed.
