### ISSUE TITLE
Mattermost icons

### ISSUE THREAD

**Issue by prcmt** [dkanada/frost#261]
There are currently two Mattermost apps available on F-Droid (somewhat dubiously labelled _Classic_ and _Beta_. I imagine both should have the same existing icon.

```
<item component="ComponentInfo{com.mattermost.rnbeta/com.mattermost.rnbeta.MainActivity}" drawable="mattermostbeta"/>
<item component="ComponentInfo{com.mattermost.mattermost/com.mattermost.mattermost.SplashScreenActivity}" drawable="mattermostclassic"/>
```

**Comment by nonnominandus** [comment]
I included these activity names in my pull request (#297) so it should be fixed soon!

**Comment by nonnominandus** [comment]
@dkanada As the new activity names are included I guess this issue could be closed.
