### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by bigtreiber** [dkanada/frost#279]
Hi,

I'm missing FOSS Browser
[20200402_051701.zip](https://github.com/dkanada/frost/files/4421927/20200402_051701.zip)

**Comment by nonnominandus** [comment]
I made an icon for it. As there seemed to be no use for the outer circle I removed it and blew up the inner globe.
![rect2043](https://user-images.githubusercontent.com/25853274/80037317-a5b14900-84f3-11ea-99a4-103f8d4cd11c.png)

**Comment by nonnominandus** [comment]
@dkana As the new icon is in place on the main branch I guess this issue could be closed.
