### ISSUE TITLE
Icon Request :)

### ISSUE THREAD

**Issue by baconicsynergy** [dkanada/frost#28]
Unfortunately, Turtl is crashing on my device :/ But here is a list of F-Droid apps with missing icons:

Archwiki Viewer
Bitcoin
Dandelion*
Good Weather
Hacker's Keyboard
Red Moon
Riot
Silence
StreetComplete
WebApps

And only one Lineage(cyanogen) icon: Theme Chooser

**Comment by conrad-heimbold** [comment]
Bitcoin, Dandelion, Red Moon, Riot, Silence and StreetComplete should already be there. 
Either, they will be released in the next version; or the activity name is wrong/has changed.

**Comment by baconicsynergy** [comment]
Okay, sounds good! Thanks for resurrecting this project, btw. This is my favorite android icon pack of all time

**Comment by nonnominandus** [comment]
@dkanada As Donnnnos pull request resolved the last icon (#251) I guess this issue can be closed.
