### ISSUE TITLE
New ReadEra icon not displaying

### ISSUE THREAD

**Issue by spaceoden** [dkanada/frost#282]
I'm running 1.7.4 and it seems the ReadEra and Rainy Mood icons I submitted for 1.7.4 are not showing up on my device. I noticed they don't appear in the various drawable-*dpi folders. Is there a script I should run before submitting a PR to populate these?

**Comment by nonnominandus** [comment]
You seem to have commented 4 days after the latest version bump (db4c71cc9d3affec186a201afbafe4a14c90ff7a). For new icons to show up on your device first the pull request has to be merged, then dkana has to make a new release, for which normally is waited to have at least a couple of new icons, after which F-Droid (I guess you use that) has to update the package in their database, which could take a couple of days, only then will the new version be availeble for download on your device, which contains your icons (hopefully).

**Comment by spaceoden** [comment]
Sorry, should have clarified: I am using the new 1.7.4 . I have the new Voice icon, but not the new ReadEra icon which I understood was merged before the release.

**Comment by nonnominandus** [comment]
Okay that makes it a bit clearer. I see you already submitted a pull request I suppose with a fix. But I never run any scripts before a pull request, only make sure the appfilter.xml entry is correctly added (with a drawable name which corresponds to the name of your svg file).

**Comment by spaceoden** [comment]
Sort of, the pull request fixes a mistake in the appfilter regarding Rainy Mood, but as far as I can tell there are no issues with ReadEra, other than its absence from the drawable-*dpi folders. Yeah it's been my experience in the past that the icons and appfilter are all that's needed.

**Comment by nonnominandus** [comment]
In that case I am sorry but I don't know how to resolve it.

**Comment by spaceoden** [comment]
added them to the icons folder instead of other, whoops.
