### ISSUE TITLE
fill-rule:evenodd: these can just be deleted - removing this breaks my icons

### ISSUE THREAD

**Issue by TobiasDev** [dkanada/frost#284]
I wanted to submit two icons and checked the doc. I have to remove "**fill-rule:evenodd**: these can just be deleted", when I delete these it breaks my shape. This is the first time I do an SVG so not sure why it breaks, any thoughts?

EDS Lite (f-droid): 
`<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M45.4737 0H2.52632C1.13107 0 0 1.13107 0 2.52632V45.4737C0 46.8689 1.13107 48 2.52632 48H45.4737C46.8689 48 48 46.8689 48 45.4737V2.52632C48 1.13107 46.8689 0 45.4737 0ZM19.7751 18.3609L17.5124 16.0982L16.2396 16.2396L16.0982 17.5124L18.3609 19.7751L19.7751 18.3609ZM25 13.8V17H23V13.8L24 13L25 13.8ZM29.8644 19.7925L32.1271 17.5298L31.9857 16.257L30.7129 16.1156L28.4501 18.3783L29.8644 19.7925ZM34.2 25H31V23H34.2L35 24L34.2 25ZM28 29.4142L30.2627 31.677L31.5355 31.5355L31.6769 30.2627L29.4142 28L28 29.4142ZM23 34.2V31H25V34.2L24 35L23 34.2ZM18.4287 28.3997L16.1659 30.6624L16.3074 31.9352L17.5802 32.0767L19.8429 29.8139L18.4287 28.3997ZM13.8 23H17V25H13.8L13 24L13.8 23ZM24 38C31.732 38 38 31.732 38 24C38 16.268 31.732 10 24 10C16.268 10 10 16.268 10 24C10 31.732 16.268 38 24 38ZM37 24C37 31.1797 31.1797 37 24 37C16.8203 37 11 31.1797 11 24C11 16.8203 16.8203 11 24 11C31.1797 11 37 16.8203 37 24Z" fill="white"/>
</svg>
`

Readrops
`<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M24 48C37.2548 48 48 37.2548 48 24C48 10.7452 37.2548 0 24 0C10.7452 0 0 10.7452 0 24C0 37.2548 10.7452 48 24 48ZM24 14C20.7284 14 17.8237 15.5711 15.9993 18H6C5.44772 18 5 18.4477 5 19V21C5 21.5523 5.44772 22 6 22H14.2C14.0689 22.6462 14 23.3151 14 24C14 24.6849 14.0689 25.3538 14.2 26H6C5.44772 26 5 26.4477 5 27V29C5 29.5523 5.44772 30 6 30H15.9993C17.8237 32.4289 20.7284 34 24 34C27.2716 34 30.1763 32.4289 32.0007 30H43C43.5523 30 44 29.5523 44 29V27C44 26.4477 43.5523 26 43 26H33.8C33.9311 25.3538 34 24.6849 34 24C34 23.3151 33.9311 22.6462 33.8 22H43C43.5523 22 44 21.5523 44 21V19C44 18.4477 43.5523 18 43 18H32.0007C30.1763 15.5711 27.2716 14 24 14ZM19.5 30C20.8807 30 22 28.8807 22 27.5C22 26.9372 21.814 26.4178 21.5002 26C21.0441 25.3928 20.3179 25 19.5 25C18.6821 25 17.9559 25.3928 17.4998 26C17.186 26.4178 17 26.9372 17 27.5C17 28.8807 18.1193 30 19.5 30ZM24 14H42C42.5523 14 43 13.5523 43 13V11C43 10.4477 42.5523 10 42 10H19C18.4477 10 18 10.4477 18 11V13C18 13.5523 18.4477 14 19 14H24ZM6 10C5.44772 10 5 10.4477 5 11V13C5 13.5523 5.44772 14 6 14H12C12.5523 14 13 13.5523 13 13V11C13 10.4477 12.5523 10 12 10H6ZM5 35C5 34.4477 5.44772 34 6 34H23C23.5523 34 24 34.4477 24 35V37C24 37.5523 23.5523 38 23 38H6C5.44771 38 5 37.5523 5 37V35ZM30 35C30 34.4477 30.4477 34 31 34H42C42.5523 34 43 34.4477 43 35V37C43 37.5523 42.5523 38 42 38H31C30.4477 38 30 37.5523 30 37V35Z" fill="white"/>
</svg>
`

**Comment by dkanada** [comment]
I think it might be the `fill=none` in the parent object causing issues.

**Comment by TobiasDev** [comment]
I'll give it a go to see. :)

**Comment by TobiasDev** [comment]
Hmm, I tried several different variants, but can't get any of them to work if I remove that. Like I wrote though, this is the first time I tried doing it, so could def. be something I've done wrong.

**Comment by dkanada** [comment]
If you look at other existing icons, I have it working with almost no properties. You should also technically be able to remove `fill-rule` and `clip-rule` from the path. Maybe you need to set the fill color to `#fff` instead of white?

**Comment by TobiasDev** [comment]
Hmm, I tried making the icons the same as the others (with the SVG Version, etc.) but as soon as I open them they look different. :(

![image](https://user-images.githubusercontent.com/5912371/78558785-82a84900-7813-11ea-8c2f-5cbe94dc6bc0.png)

Like I wrote, first time trying to make icons in SVG format, so not sure what I have done wrong, but clearly something. :)

**Comment by dkanada** [comment]
It's probably fine, SVGs aren't large anyways so a bit more data doesn't hurt.

**Comment by dkanada** [comment]
The main benefit is easy manipulation in the future, but masks would also help that, which I haven't looked into for my scripts.

**Comment by TobiasDev** [comment]
Okay, so am I fine to submit with the extra data?

**Comment by dkanada** [comment]
Yeah that's fine, don't worry.

**Comment by TobiasDev** [comment]
Submitted in: https://github.com/dkanada/frost/pull/285
