### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by limakolas** [dkanada/frost#286]
- Carnet
- Currency
- Talalarmo
- Tuner
[20200407_113802.zip](https://github.com/dkanada/frost/files/4443313/20200407_113802.zip)

**Comment by nonnominandus** [comment]
Okay I made them, although I am not so sure about the currency one. The icon I made now should be usable in the sense that it would be recognisable but maybe it does not really fit in the design of this iconpack. If anyone has an idea (or maybe a sketch on paper) I would like to hear and give it another try.
![rect955](https://user-images.githubusercontent.com/25853274/80032613-b958b180-84eb-11ea-91b0-1ea700df15dd.png)

**Comment by limakolas** [comment]
thank you very much! I like it a lot!
