### ISSUE TITLE
Icon Request: EDS-Lite, GeekRSS, Librera Reader, Scanbot, Tiny Tiny RSS and Simple Voice Recorder

### ISSUE THREAD

**Issue by TobiasDev** [dkanada/frost#292]
I did try doing them myself but without any luck, so figured someone better than me will do a waaaaayyyy better job. :D 

Icons in the .zip

- EDS-Lite, F-Droid
- GeekRSS, Issy-Droid through F-Droid
- Librera Reader, F-Droid
- ScanBot, Google Play Store
- Tiny Tiny RSS, F-Droid
- Simple Voice Recorder, F-Droid

[20200416_092232.zip](https://github.com/dkanada/frost/files/4485485/20200416_092232.zip)

**Comment by Donnnno** [comment]
Adding them my next pull request!

**Comment by nonnominandus** [comment]
@dkana As all icons are included on the main branch now I guess this issue could be closed.
