### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by cold412** [dkanada/frost#296]
- Altcoin Prices
- Fruux
- Lloyds Bank
- OpenBoard
- Revolut
- Suntimes Calendars
[icons.zip](https://github.com/dkanada/frost/files/4519007/icons.zip)

**Comment by Donnnno** [comment]
Just created 4 of the icons from this request #293 
- [x] Altcoin Prices
- [x] Fruux
- [ ] Lloyds Bank
- [x] OpenBoard
- [ ] Revolut
- [x] Suntimes Calendars

![afbeelding](https://user-images.githubusercontent.com/31142286/80247809-fb5e3080-866e-11ea-958a-25ced3374d00.png)

**Comment by cold412** [comment]
Awesome!!! thx!!!

**Comment by nonnominandus** [comment]
![preview4](https://user-images.githubusercontent.com/25853274/81702406-8448da80-946b-11ea-8fe7-3b27a6fc368e.png)
I created the last two icons. These will be included in my next pull request.

**Comment by Donnnno** [comment]
Maybe remove the text from the horse icon?

**Comment by cold412** [comment]
> Maybe remove the text from the horse icon?

Yeah! should be better maybe there is another one for business or something.

**Comment by cold412** [comment]
> ![preview4](https://user-images.githubusercontent.com/25853274/81702406-8448da80-946b-11ea-8fe7-3b27a6fc368e.png)
> I created the last two icons. These will be included in my next pull request.

Awesome, great work! Thank you!

**Comment by nonnominandus** [comment]
![preview5](https://user-images.githubusercontent.com/25853274/81786358-cfacc880-94ff-11ea-8adb-a065df860af7.png)
I agree with the removal of the text from the icon.

**Comment by nonnominandus** [comment]
![preview6](https://user-images.githubusercontent.com/25853274/81789505-5e234900-9504-11ea-96ad-affe1220e8d2.png)
I guess that without the text the outer circle could also be removed.

**Comment by cold412** [comment]
> ![preview6](https://user-images.githubusercontent.com/25853274/81789505-5e234900-9504-11ea-96ad-affe1220e8d2.png)
> I guess that without the text the outer circle could also be removed.

Yeah! should be fine. thx!

**Comment by mamg22** [comment]
@dkanada This request seems to be fully completed and included in the icon pack, maybe this issue can now be closed?

**Comment by cold412** [comment]
yes, sorry for late reply. Thank you for your work.
