### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by yekteniya** [dkanada/frost#306]
All of the following are F-Droid apps:
- Waistline
- ProtonVPN
- LibreTorrent
- DecSync CC

Thank you!
[IconRequest.zip](https://github.com/dkanada/frost/files/4603519/IconRequest.zip)

**Comment by nonnominandus** [comment]
![preview2](https://user-images.githubusercontent.com/25853274/81698625-8c524b80-9466-11ea-8c0f-5924628a412c.png)
I drew them, I will include them in my next pull request.

**Comment by nonnominandus** [comment]
I should have looked but I saw that protonVPN and LibreTorrent were already in place, so I added the activity names you submitted (which will make the icons work for you) and reused the old icons. But they are essentially the same:
![preview3](https://user-images.githubusercontent.com/25853274/81699220-52ce1000-9467-11ea-998b-da3bbc7ba77b.png)

**Comment by yekteniya** [comment]
After updating the app to 1.8.0, I can't see the DecSync CC icon.

I believe this has to do with a typo in the code, as the drawable is "decsyn**ccc**" but the icon is  "decsyn**cc**.svg"

**Comment by Donnnno** [comment]
fixed the typo in my pr #334
