### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by pasdechance** [dkanada/frost#308]
[20200515_091150.zip](https://github.com/dkanada/frost/files/4636698/20200515_091150.zip)

A few missing icons. I might try and do one or two once I remember how to use Inkscape.

List generated by Turtl.

7Speaking
Banque
Feedly Classic
Find Device
Fossil Hybrid
Freebox
Imaging Edge Mobile
JuiceSSH
LinkedIn
Motorola Notifications
My NEOMA BS
OneDrive
Rewards

**Comment by nonnominandus** [comment]
![preview10](https://user-images.githubusercontent.com/25853274/82457022-3c523500-9ab5-11ea-8e4c-a126f601071d.png)
I drew all the missing icons, let me know what you think of them!

**Comment by pasdechance** [comment]
They look great to me. Especially the Juice icon.
