### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Emevo** [dkanada/frost#309]
I would like to request a few icons:

AudioAnchor
Khan Academy
MobilePay
NemID
Nordnet
PlantNet
Rejseplanen
TooGoodToGo

[20200516_102835.zip](https://github.com/dkanada/frost/files/4639203/20200516_102835.zip)

**Comment by nonnominandus** [comment]
![preview11](https://user-images.githubusercontent.com/25853274/82802734-a9801480-9e7f-11ea-8a9b-0b6be15688ee.png)
I drawed the icons, if you have any comments or suggestions please feel free to paste them here! I am not very sure about the toogootogo one (bottom-right) so if anyone has other ideas for it please share.

**Comment by Emevo** [comment]
Thanks alot i think the icons look great.
About rejseplanen, now that it is black and white I see that it looks quite like a pokeball.  I never really thought about it before. Maybe it would be a good idea to make it square like in the attached picture to make it a bit more different.
About the toogoodtogo icon, maybe small white lines where the different green tones meet would make it more distinct? But i am not sure about this one.

But again, thanks alot for making these icons!

![Screenshot from 2020-05-25 15-56-30](https://user-images.githubusercontent.com/19559106/82820637-de519300-9ea2-11ea-8b40-6109a94c0e36.png)

**Comment by nonnominandus** [comment]
![preview12](https://user-images.githubusercontent.com/25853274/83055846-b6099600-a054-11ea-876f-53f5f6fbee3b.png)
I created both variants as you proposed and they indeed are better! I included them in my pull request.

**Comment by Emevo** [comment]
Thanks a lot they look great!
