### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by humblelion13** [dkanada/frost#314]
Aard 2
AIMP
Alarmio
APK Kit
Explorer
FFUpdater
Firefox Preview
OpenVPN Connect
ReadEra
Root Explorer
SAI
SD Maid
Wifi Key View
[20200529_042715.zip](https://github.com/dkanada/frost/files/4700532/20200529_042715.zip)

**Comment by Donnnno** [comment]
Every icon is added to my pr: #334 some icons were already in place. 

- [x] Aard 2
- [x] AIMP
- [x] Alarmio
- [x] APK Kit
- [x] Explorer
- [x] FFUpdater
- [x] Firefox Preview
- [x] OpenVPN Connect
- [x] ReadEra
- [x] Root Explorer
- [x] SAI
- [x] SD Maid
- [x] Wifi Key View
