### ISSUE TITLE
Icon Request: Everdo, Simple Dialer, Simple SMS and Collabora

### ISSUE THREAD

**Issue by TobiasDev** [dkanada/frost#316]
Icon request for:
- Simple Dialer
- Simple SMS
- Everdo
- Collabora

[20200703_035037.zip](https://github.com/dkanada/frost/files/4867337/20200703_035037.zip)

**Comment by Donnnno** [comment]
Added these icons to my pr: #334 
- [x]     Simple Dialer
- [x]     Simple SMS
- [x]     Everdo
- [x]     Collabora
