### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by phwright** [dkanada/frost#318]
[20200614_045022.zip](https://github.com/dkanada/frost/files/4776501/20200614_045022.zip)
Droidshows
libretorrent 
pegasus
quran
whatsapp web to go 

In the future I would like to try and make some icons after I get familiar with drawing and inkscape.

**Comment by Donnnno** [comment]
Made 2 icons (pegasus, whatapp wtg), quran is the only one missing now but that one was too hard to do for me. #334 

- [x] Droidshows
- [x] libretorrent
- [x] pegasus
- [ ] quran
- [x] whatsapp web to go

**Comment by Donnnno** [comment]
Added icon for Quran.

![image](https://user-images.githubusercontent.com/31142286/89105689-ad05be00-d423-11ea-9092-7a5a9ca320f1.png)
