### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by aintyourcat** [dkanada/frost#319]
[20200615_104116.zip](https://github.com/dkanada/frost/files/4779934/20200615_104116.zip)

**Comment by Donnnno** [comment]
Updated the filter lists & created new icons:

![image](https://user-images.githubusercontent.com/31142286/88222144-d2493e00-cc65-11ea-90b2-6caf9b4e1efb.png)

I only didn't create the Kamusku icon because I didn't have any inspiration how to create it with one color :s

**Comment by aintyourcat** [comment]
Man! those icon are legit! Pull request?

Pada tanggal Rab, 22 Jul 2020 pukul 19.55 Donno <notifications@github.com>
menulis:

**Comment by Donnnno** [comment]
Added icon for Kamusku

**Comment by aintyourcat** [comment]
Thanks! They look neat! Could you make for these too?
[20200812_093913.zip](https://github.com/dkanada/frost/files/5060167/20200812_093913.zip)
