### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by kingtysonsworld** [dkanada/frost#320]
Thank you for making such a wonderful app icon pack! Here are some icon requests in the Turtl zip file.

[TwelF icon pack requests.zip](https://github.com/dkanada/frost/files/4789147/TwelF.icon.pack.requests.zip)

**Comment by Donnnno** [comment]
Added some icons in my pr: #334 

- [x] ACM
- [ ] Amino
- [ ] Ceri Launcher
- [ ] Homebase
- [ ] Hoopla
- [ ] MediBang Paint
- [x] MEGA
- [ ] Moon+ Reader Pro
- [ ] Notepad
- [x] Pastebin
- [x] Phone Manager
- [ ] RBdigital
- [ ] Sora
- [ ] Wattpad
- [x] Windscribe
