### ISSUE TITLE
Letters & Numbers for missing icons

### ISSUE THREAD

**Issue by Donnnno** [dkanada/frost#335]
I had this idea a while ago to add letter & number icons that people can use for missing icons & stuff.
Here's an example from what they can look like, I used OpenSans as font.

![image](https://user-images.githubusercontent.com/31142286/87976370-4b615d80-cacd-11ea-9d4d-3b78d3d5a9d0.png)

Let me know what you think :^)

**Comment by nonnominandus** [comment]
I think it looks cool. I myself would not want to use them (I would just draw the icons myself) but if you all think they will be used and appreciated I vote in favor of including this into frost.
