### ISSUE TITLE
Icon Request: Fake Traveler

### ISSUE THREAD

**Issue by plambros** [dkanada/frost#338]
https://f-droid.org/en/packages/cl.coders.faketraveler/

https://github.com/mcastillof/FakeTraveler

```
<!-- Fake Traveler -->
<item component="ComponentInfo{cl.coders.faketraveler/cl.coders.faketraveler.MainActivity}" drawable="faketraveler"/>
```

**Comment by Donnnno** [comment]
Hi, I've updated this icon and added the code line.
Old → new
![image](https://user-images.githubusercontent.com/31142286/89105857-294cd100-d425-11ea-8d77-e6f67f9b8248.png)

It's in my pr: #334
