### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by bigbavarian** [dkanada/frost#345]
`<!--` ClassyShark3xodus -->
<item component="ComponentInfo{com.oF2pks.classyshark3xodus/com.oF2pks.applicationsinfo.MainActivity}" `drawable="classyshark3xodus"/>`

**Comment by bigbavarian** [comment]
`
<item component="ComponentInfo{com.aurora.adroid/com.aurora.adroid.ui.generic.activity.SplashActivity}" drawable="auroradroid"/>`

**Comment by Donnnno** [comment]
Hi, I've added the Aurora droid line in my pr: #334 , the ClassyShark3xodus line is already in there.

**Comment by bigbavarian** [comment]
ClassyShark installed 2 Apps in my s7. One was with the frost icon but the other has an different one. so i added the turtel information here. that other APP shows informations about installed apps.
