### ISSUE TITLE
Icon Request: Pintrest, e.foundation camera, Element chat and Aurora Droid

### ISSUE THREAD

**Issue by TobiasDev** [dkanada/frost#348]
Hello, some more icons I would love to see added.

- Element (RiotX)
- e.foundation: Apps (App store)
- e.foundation: Camera (Based on Open Camera)
- Pintrest
- Aurora Droid

[20200810_101413.zip](https://github.com/dkanada/frost/files/5053143/20200810_101413.zip)

**Comment by Donnnno** [comment]
Element, Aurora Droid are already in the appfilter, I've added Camera too.
- [x]     Element (RiotX)
- [ ]     e.foundation: Apps (App store)
- [x]     e.foundation: Camera (Based on Open Camera)
- [ ]     Pintrest
- [x]     Aurora Droid
