### ISSUE TITLE
Icon Request 

### ISSUE THREAD

**Issue by aintyourcat** [dkanada/frost#349]
Hello, i would like to request icons for some apps. Here's the list:

1. AIDS
2. Calendar
3. Notification CRON
4. PicSayPro
5. YetAnotherVideoPlayer

And this the file: [20200812_093913.zip](https://github.com/dkanada/frost/files/5067484/20200812_093913.zip). Thanks.

**Comment by Donnnno** [comment]
I've created these icons (calendar is already applied). I'm gonna in a pull request soon!

![image](https://user-images.githubusercontent.com/31142286/91981910-ca32f280-ed29-11ea-91f3-367bd6ba0bdc.png)


- [x] AIDS
- [x] Calendar
- [x] Notification CRON
- [x] PicSayPro
- [x] YetAnotherVideoPlayer

**Comment by Donnnno** [comment]
Hi, it means the icon should already work! It currently uses this one: https://github.com/dkanada/frost/blob/master/icons/calendar.svg
