### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by kaliangel** [dkanada/frost#350]
- Alarmio
- Element
- Fallout Shelter
- Flym
- ImgurViewer
- InstaGrabber
- Ma Livebox
- Metro
- Nebulo
- Syphon
- TrackerControl
- usageDirect
- Warden

ZIP file : https://github.com/kaliangel/frost/blob/master/20200813_033059.zip

**Thanks !**

**Comment by Donnnno** [comment]
Alarmio, Alarmio & TrackerControl are already in my pr: #334

**Comment by Donnnno** [comment]
Hi, can you upload the zip file again? I noticed that it's gone.

**Comment by kaliangel** [comment]
> Hi, can you upload the zip file again? I noticed that it's gone.

Can you see it now ? @Donnnno

**Comment by Donnnno** [comment]
Yes, thanks!

**Comment by Donnnno** [comment]
Created all the icons, gonna put them in my next pr!

- [ ]     Alarmio
- [ ]     Element
- [ ]     Fallout Shelter
- [ ]     Flym
- [ ]     ImgurViewer
- [ ]     InstaGrabber
- [ ]     Ma Livebox
- [ ]     Metro
- [ ]     Nebulo
- [ ]     Syphon
- [ ]     TrackerControl
- [ ]     usageDirect
- [ ]     Warden

![image](https://user-images.githubusercontent.com/31142286/93488565-cba61280-f906-11ea-8616-b5b3568e8136.png)
