### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by CrazyMarvin** [dkanada/frost#354]
- [Ella - The Game](https://github.com/Crazy-Marvin/EllaTheGame)
rocks.poopjournal.Ella/com.unity3d.player.UnityPlayerActivity

- [Flashy](https://github.com/Crazy-Marvin/Flashy)
rocks.poopjournal.flashy/com.poopjournal.flashy.MainActivity

- [Pimple Popper](https://github.com/Crazy-Marvin/PimplePopper)
rocks.poopjournal.pimplepopper/com.godot.game.GodotApp

**Comment by Donnnno** [comment]
Hi, do you also have the icons from the apps?

**Comment by CrazyMarvin** [comment]
Hey, does the attached .zip help?

[IconRequest.zip](https://github.com/dkanada/frost/files/5178887/IconRequest.zip)

**Comment by CrazyMarvin** [comment]
Here are the source files: 
[Icons.zip](https://github.com/dkanada/frost/files/5254985/Icons.zip)

**Comment by Donnnno** [comment]
Thanks for providing the source icons, this is what I made with it:

(can you provide the activity names for Mirry & metadata remover too?)

![image](https://user-images.githubusercontent.com/31142286/93765564-678c9280-fc15-11ea-9eb6-18bbc7293d50.png)

**Comment by CrazyMarvin** [comment]
Your icons look awesome!

Metadata Remover: rocks.poopjournal.metadataremover/rocks.poopjournal.metadataremover.ui.MainActivity
Mirry: rocks.poopjournal.mirry/rocks.poopjournal.mirry.MainActivity

The Metadata Remover icon is already in the icon pack. I put it in the .zip by accident. Sorry for that. But I like the design here more, maybe you can make it the default and the existing one an alterantive?

**Comment by Donnnno** [comment]
Thanks, added them to my pull request :)
