### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by r031n** [dkanada/frost#357]
<item component="ComponentInfo{se.leap.bitmaskclient/se.leap.bitmaskclient.StartActivity}" drawable="bitmask"/>

<item component="ComponentInfo{com.example.tobiastrumm.freifunkautoconnect/com.example.tobiastrumm.freifunkautoconnect.MainActivity}" drawable="freifunkautoconnect"/>

<item component="ComponentInfo{de.freifunk_karte.freifunk_karte/de.freifunk_karte.freifunk_karte.FreifunkMap}" drawable="freifunk-karte"/>

<item component="ComponentInfo{de.eos.uptrade.android.fahrinfo.hamburg/de.hafas.main.HafasApp}" drawable="hvv"/>

<item component="ComponentInfo{org.codeaurora.snapcam/com.android.camera.CameraLauncher}" drawable="kamera"/>

<item component="ComponentInfo{me.twrp.twrpapp/me.twrp.officialtwrpapp.activities.MainActivity}" drawable="officialtwrpapp"/>

<item component="ComponentInfo{com.starfinanz.mobile.android.pushtan/com.starfinanz.mobile.android.spushtan.SPushTan}" drawable="pushtan"/>

<item component="ComponentInfo{de.stadtrad.hamburg/de.stadtrad.hamburg.StadtRadHamburgActivity}" drawable="stadtradhamburg"/>

**Comment by Donnnno** [comment]
Hi, this request is empty. We can't do anything with this now.
