### ISSUE TITLE
[Icon Request] - ADAC Spritzpreise, pleestracker and NextCloud Cookbook

### ISSUE THREAD

**Issue by TobiasDev** [dkanada/frost#362]
Some more icons I would love to have!

- [ ] ADAC Spritzpreise
- [ ] Pleestracker (sleeping tracker from F-Droid)
- [ ] NextCloud Cookbook

[20200913_064317.zip](https://github.com/dkanada/frost/files/5213629/20200913_064317.zip)

**Comment by Donnnno** [comment]
Added these & the icons from your other request to my pr: #366 

![image](https://user-images.githubusercontent.com/31142286/95102654-ec0e0380-0733-11eb-85ab-a4f75c20ffaa.png)
