### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by Manothave** [dkanada/frost#373]
Superfreez, Taobao, Alibaba, Open board, App manager, riseupvpn , office, open keyboard, invisible pro, kindle, capcut, v2rayng, multivnc, grammarly keyboard

**Comment by Donnnno** [comment]
Can you provide the icons and follow the following steps:

> This app doesn't have an icon request feature, so you'll have to do the following steps.
> 
> Install Turtl which can extract the icons and class names of your apps.
> Open Turtl and follow the process to save the new zip file to your phone.
> Make an issue titled "Icon Request" and attach the zip file.
> 
> If Turtl is not working on your device, you can also use Applications Info or any equivalent app to collect the package name of the app ($PACKAGE_NAME) and the main activity name of the app ($ACTIVITY_NAME) launchable in Applications Info with no errors. Work is being done to simplify this process.
