### ISSUE TITLE
Expirimenting with lines

### ISSUE THREAD

**Issue by Donnnno** [dkanada/frost#375]
Hi, not an icon request but something different ;) 

I'm experimenting a bit with the code in android studio to get an idea how this icon pack stuff works. I'm not a coder, so I do things step by step. 

Currently, I'm trying to make line variants based on the frost icons!
Maybe eventually I'll convert every icon (it takes some time because of adjusting shapes and a lot of resizing), there are ~250 icons already converted.

Here's an example how it will look:
![image](https://user-images.githubusercontent.com/31142286/96520541-9c6d2300-126f-11eb-8471-b0aa5f56d375.png)

:)

**Comment by bigbavarian** [comment]
looks nice :)

**Comment by radasbona** [comment]
The existing Busybox icon looks almost like this.

I like the "line style" very much. Maybe a second icon pack is possible? "Frost Lines" or something like that?

**Comment by Donnnno** [comment]
Yeah, I was thinking about doing that, already converted a lot of icons (~500 now).

**Comment by Donnnno** [comment]
Another update, there are around 836 icons now. I've updated a lot of them, better sizing (more balance), redesigned some old icons, created a simple line font for the icons and removing some old really cluttered icons. Still have to clean up & convert some of them (a lot of svg's show empty documents when opening). 

![image](https://user-images.githubusercontent.com/31142286/97724090-c8d53a80-1acc-11eb-8fe8-f1258c681e6a.png)
![image](https://user-images.githubusercontent.com/31142286/97723797-7562ec80-1acc-11eb-8cdc-4c67add7fe63.png) 
![image](https://user-images.githubusercontent.com/31142286/97723819-798f0a00-1acc-11eb-836a-5ae17572bbfc.png)

**Comment by dkanada** [comment]
Wow you are a beast! :laughing: I've thought about turning this into an organization for a while to combine all the FOSS icon packs on F-Droid but always figured it was too niche to gain any traction.

**Comment by Donnnno** [comment]
Haha, maybe it's a niche yea. But I'm pretty close to submitting it to f-droid now :) Still have some work to do but the repo is public now: https://github.com/Donnnno/frost-lines

**Comment by dkanada** [comment]
No need to use this app in the name if you can think of a better one. Perhaps "Leylines" or "Wiring" or something.

**Comment by Donnnno** [comment]
Yea still thinking about that, thanks :)

**Comment by dkanada** [comment]
If you want to stray a bit more from this pack, pulling a single color from each icon might look really nice. One of my gripes with this one sometimes is that the icons can be a bit hard to distinguish since they're monochrome.

**Comment by Donnnno** [comment]
Hmm, yea that's a good suggestion. I'll keep that in mind! As for at least this one has white lines (I've managed to submit it to F-Droid, still waiting for it to be published tho).

**Comment by Donnnno** [comment]
Time to close this issue because version 1.0.0 is available on F-Droid!! 🎉
