### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by warpedwood** [dkanada/frost#379]
[20201023_103953.zip](https://github.com/dkanada/frost/files/5431781/20201023_103953.zip)
Hi, I'm sorry to come back with the same icon but it seems that the code changed and it doesn't work anymore. I also antennapod as they changed their icon. Thanks again for your great work!

**Comment by baitmooth** [comment]
antennapod is in my PR #472

**Comment by baitmooth** [comment]
- [x] banque
- [x] antennapod
