### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by ungeskriptet** [dkanada/frost#383]
[20201024_082039.zip](https://github.com/dkanada/frost/files/5433530/20201024_082039.zip)

- Bluetooth Keyboard & Mouse
- KeePassDX
- MultiVNC
- mydealz
- MyFRITZ!
- QR & Barcode Scanner
- SuperTuxKart

**Comment by baitmooth** [comment]
- [x] Bluetooth Keyboard & Mouse
- [x] KeePassDX
- [x] MultiVNC
- [ ] mydealz
- [x] MyFRITZ!
- [x] QR & Barcode Scanner
- [x] SuperTuxKart

Some of them added in #475

**Comment by baitmooth** [comment]
![383-2021-06-22-1000](https://user-images.githubusercontent.com/23211478/122895000-016da100-d348-11eb-845a-87954bc733ee.png)
