### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Nolanderthal** [dkanada/frost#388]
[20201108_093540.zip](https://github.com/dkanada/frost/files/5507796/20201108_093540.zip)

Request for:

Nine (Email app)
Wells Fargo
Privacy
Mullvad VPN
Freez

**Comment by Donnnno** [comment]
Hi! I've created the icons, gonna add it in my next pull request together with some other ones.

![image](https://user-images.githubusercontent.com/31142286/101032133-189a9c00-357a-11eb-9a8e-35641c27c2c9.png)

**Comment by Nolanderthal** [comment]
These look great. Thank you!
