### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by jackhiggins458** [dkanada/frost#394]
[20201122_081258.zip](https://github.com/dkanada/frost/files/5579219/20201122_081258.zip)
Hi! Love your work with this icon pack. Just a few more suggestions here. Would love to see the DuckDuckGo and Calyx VPN get icons in particular, think these apps will be/already are quite popular. Thanks so much for your efforts mate : )

**Comment by Donnnno** [comment]
Hi! I've created the icons, gonna add it in my next pull request together with some other ones.

![image](https://user-images.githubusercontent.com/31142286/101042743-cf4c4b80-357d-11eb-9932-ddfe93049ed5.png)

**Comment by jackhiggins458** [comment]
Awesome, looks great! Thanks for this :)
