### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by alanpearce** [dkanada/frost#4]
[Turtl](https://github.com/dkanada/ICEcons/files/1028736/20170525_123144.zip)

**Comment by Donnnno** [comment]
Here's a list with the icons , the strikethrough apps are in the icon pack.

- ~~Bitcoin~~
- ~~Browser~~
- ~~Citymapper~~
- DNS66
- ~~Files~~
- ~~Good Weather~~
- Meditation Assistant
- ~~Mein Vodafone~~
- ~~N26~~
- ~~oandbackup~~
- Omni Notes FOSS
- QuickDic
- ~~Simple Weather~~
- ~~Sleep~~
- Sleep Cycle
- ~~Tidal~~
- ~~Wire~~
