### ISSUE TITLE
Icon Request: Authenticator Pro

### ISSUE THREAD

**Issue by TobiasDev** [dkanada/frost#405]
[20201226_075050.zip](https://github.com/dkanada/frost/files/5742786/20201226_075050.zip)

**Comment by z4-xz** [comment]
![summary_authenticator](https://user-images.githubusercontent.com/54031551/103529765-89d5b380-4e86-11eb-80e7-7f8c7cd7e5c4.png)

**Comment by dkanada** [comment]
@TobiasDev is that the only icon you requested in this issue? Let me know if I should close it.

**Comment by TobiasDev** [comment]
> 
> 
> @TobiasDev is that the only icon you requested in this issue? Let me know if I should close it.

Yep, I created separate issues for the other icons since I request them at different times. :)
