### ISSUE TITLE
code changes

### ISSUE THREAD

**Issue by dkanada** [dkanada/frost#408]
@Donnnno I made some changes to the code that might be useful in your app as well. If you want to convert the `ic_*` icons to SVGs I can also update the menu to better support color changes in the future.

**Comment by Donnnno** [comment]
That sounds pretty cool! I'll take a look if I can implement your changes. 

Btw, there's someone who's gonna take a look at a search feature for the app, that might be useful for you too :)

**Comment by Donnnno** [comment]
@dkanada also a small question: Do you know if F-Droid auto-detects GitHub releases? Or do I have to notify it somewhere?

**Comment by dkanada** [comment]
It was a bunch of minor stuff like improving the build configuation, fixing some duplicate strings, and pulling the button styling out into a custom element so we don't need half a page for every single button. There's still way too much code for the interface but this should at least improve things. I'll have another commit soon with more code reduction.

**Comment by dkanada** [comment]
I think it detects the tags, not the releases.

**Comment by Donnnno** [comment]
Ah okey, I think I did it right then :) thanks

**Comment by Donnnno** [comment]
I've implemented your code, it looks pretty good :)

**Comment by Donnnno** [comment]
also how does the raster script work? I'm getting an error (I have inkscape installed).
`raster.sh: line 17: inkscape: command not found`

**Comment by dkanada** [comment]
What distro are you using? I wrote these scripts back when I was using `sh` to run tools instead of `bash` so I think there are some quirks due to that decision. Otherwise, I would guess it's a `PATH` issue for the Inkscape binary, which is unrelated to the script itself.

**Comment by Donnnno** [comment]
Ah okey, I'm using windows with git bash to run the other scripts. But if it doesn't work I always can use the illustrator export options instead (it takes more time to do it that way).

**Comment by Donnnno** [comment]
@dkanada A friend of mine added a search function to the app, might be useful for you as well :)
