### ISSUE TITLE
Icons don't work using v2.0.1

### ISSUE THREAD

**Issue by mamg22** [dkanada/frost#410]
Just updated to version 2.0.1 from F-Droid and none of the icons are being applied. Already tried:

* Restarting launcher (Lawnchair from Play Store), also cleared cache.
* Rebooting phone.
* Reinstaling Frost.
* Tried another launcher (KISS and OpenLauncher from F-Droid), neither worked.

Opening the Frost app and tapping on the "Icons" menu shows ![this](https://user-images.githubusercontent.com/45301823/103448078-7bab4b80-4c6a-11eb-8353-93be1d517eb6.png), which looks like the icons or some metadata is missing.

Using a Xiaomi Redmi 7A, running MIUI 10.

F-Droid downloaded apk is about 2.7 MiB.

Edit: Extracted the apk from my phone, unzipped it and looked at the .png files in some drawable directories. Most of them have a very small filesize (few bytes) and a size of 1x1.

**Comment by theoasispc** [comment]
Its broken for me too (Lawnchair) (Icons not showing up at all)

**Comment by mamg22** [comment]
I guess this issue was caused by the use of `shrinkResources` in the `build.gradle` file, which seems to throw away unused resources. Maybe it considers most of the icons as unused.

**Comment by dkanada** [comment]
Oops, I suppose that would cause issues. @Donnnno don't add that property to your manifest haha.

**Comment by dkanada** [comment]
I've pushed a new release to hopefully fix this, it should be on F-Droid in the next few days.

**Comment by theoasispc** [comment]
> I've pushed a new release to hopefully fix this, it should be on F-Droid in the next few days.

Thanks :)

**Comment by Donnnno** [comment]
@dkanada oof, luckily I didn't change anything in my `build.gradle`. And I'm using a debug version of my app from android studio so nothing did break for me :)

**Comment by mamg22** [comment]
v2.0.2 is now available on F-Droid and the icons are working again. Thanks @dkanada
