### ISSUE TITLE
Is v2.0.1 broken?

### ISSUE THREAD

**Issue by forkbomb9** [dkanada/frost#411]
Just updated to Frost v2.0.1, and the icons were reset to default. Downgraded to v2.0.0, works again.

I can reproduce this on both AOSiP 10 (Kronic Launcher, close to AOSP) and Android 8.1 (Lawnchair).

**Comment by theoasispc** [comment]
Its broken for me too (Lawnchair) (Icons not showing up at all)

**Comment by dkanada** [comment]
closing in favor of #410

**Comment by forkbomb9** [comment]
Oops. Kept that "New Issue" tab open for too long 😉
