### ISSUE TITLE
Icon request - Snippet

### ISSUE THREAD

**Issue by Donkey-Doug** [dkanada/frost#492]
Snippet

[20210704_062051.zip](https://github.com/dkanada/frost/files/6760203/20210704_062051.zip)

**Comment by baitmooth** [comment]
![492-2021-07-07-1505](https://user-images.githubusercontent.com/23211478/124766993-b488ed80-df37-11eb-87b8-930fb5d79028.png)

**Comment by Donkey-Doug** [comment]
Thank you.
