### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by alvarezprado** [dkanada/frost#69]
I found a few FLOSS apps icons missing. Actually, I think most of them can be included by just mapping app names to already existing icons (FirefoxKlar, SealNote, Feeder...), I don't think it would be a problem to use the same icon for two different apps that do esentially the same thing.

Thanks a lot and keep the great work!
[20171109_015155.zip](https://github.com/dkanada/frost/files/1457623/20171109_015155.zip)

**Comment by nonnominandus** [comment]
I made the missing ones and will in my next pull request include them.

**Comment by alvarezprado** [comment]
Amazing, thank you very much!!!! :)
