### ISSUE TITLE
Create a server component to accept icon requests and generate the xml files.

### ISSUE THREAD

**Issue by dkanada** [dkanada/frost#70]
@conrad-heimbold @ikocevski @xphnx @beli3ver It would take quite a bit of work but would definitely be worth it if more than one icon pack used the server for icon requests. I would be completely fine developing and hosting the server for anyone developing a FOSS icon pack, just want to gauge interest before I consider it. Does anyone know of any other icon packs that would benefit from this or any other PHP or node devs who would be interested in such a project? The idea came from [this](https://polar.aidanfollestad.com/) project. @xphnx and @beli3ver let me know if you aren't interested in hearing about updates to this project, I try to keep you guys in the loop since we share the same codebase. @conrad-heimbold your repo to scrape F-Droid metadata would be an excellent way to populate a database for this project.

**Comment by beli3ver** [comment]
I am interested!

**Comment by xphnx** [comment]
Great!. I am interested. Tomorrow i will write some thoughts.

El 12 de noviembre de 2017 6:33:38 CET, dkanada <notifications@github.com> escribió:
>@conrad-heimbold @ikocevski @xphnx @beli3ver It would take quite a bit
>of work but would definitely be worth it if more than one icon pack
>used the server for icon requests. I would be completely fine
>developing and hosting the server for anyone developing a FOSS icon
>pack, just want to gauge interest before I consider it. Does anyone
>know of any other icon packs that would benefit from this or any other
>PHP or node devs who would be interested in such a project? The idea
>came from [this](https://polar.aidanfollestad.com/) project. @xphnx and
>@beli3ver let me know if you aren't interested in hearing about updates
>to this project, I try to keep you guys in the loop since we share the
>same codebase. @conrad-heimbold your repo to scrape F-Droid metadata
>would be an excellent way to populate a database for this project.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dkanada/frost/issues/70

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by xphnx** [comment]
I use the icon requests for Turtl, in my experience, it might seem that it would make things easier, but it has some design problems although the fundamental problem I find is when discriminating between requests that include FLOSS or non-free apps. It could be solved by crossing the packageid of the requests with the packageid of the apps hosted on fdroid https://gitlab.com/fdroid/fdroiddata/blob/master/stats/known_apks.txt
I have definitely stopped using Turtl for this.

The idea of @conrad-heimbold in my opinion is the best way to go, so that we have the updated appfilter scraping the data directly from fdroid and the apps. So we would only have to deal with the icons, mounting the xml from the list of icons with the scripts that we currently have.

What type of server are you thinking of?

**Comment by beli3ver** [comment]
What you think about modi the turtl APP. In request the user select the icon theme, then it will create a issue in the repo.

Or it will create a entry in a database. A script checks which icon theme doesn't support this APP an then the maintainer geht a notice.

Am 13. November 2017 10:52:14 MEZ schrieb xphnx <notifications@github.com>:
>I use the icon requests for Turtl, in my experience, it might seem that
>it would make things easier, but it has some design problems although
>the fundamental problem I find is when discriminating between requests
>that include FLOSS or non-free apps. It could be solved by crossing the
>packageid of the requests with the packageid of the apps hosted on
>fdroid
>https://gitlab.com/fdroid/fdroiddata/blob/master/stats/known_apks.txt
>I have definitely stopped using Turtl for this.
>
>The idea of @conrad-heimbold in my opinion is the best way to go, so
>that we have the updated appfilter scraping the data directly from
>fdroid and the apps. So we would only have to deal with the icons,
>mounting the xml from the list of icons with the scripts that we
>currently have.
>
>What type of server are you thinking of?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dkanada/frost/issues/70#issuecomment-343867206

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by dkanada** [comment]
Scraping F-Droid is one option but an issue arises when someone uses default apps or sideloaded apps. I definitely want to include icons for certain other apps like the Lineage camera, FastHub, or Magisk, but I am still not sure where to draw the line for support, and this is a huge factor in the server design.

I am familiar with PHP and node so I was thinking of using one of those. I don't think submitting the requests over github is very useful, so I would rather add the requests to a database and include a web interface to view and manage the requests.

**Comment by beli3ver** [comment]
Then make PHP there I can help you. So make the request to thr database.

Am 13. November 2017 18:20:19 MEZ schrieb dkanada <notifications@github.com>:
>Scraping F-Droid is one option but an issue arises when someone uses
>default apps or sideloaded apps. I definitely want to include icons for
>certain other apps like the Lineage camera, FastHub, or Magisk, but I
>am still not sure where to draw the line for support, and this is a
>huge factor in the server design.
>
>I am familiar with PHP and node so I was thinking of using one of
>those. I don't think submitting the requests over github is very
>useful, so I would rather add the requests to a database and include a
>web interface to view and manage the requests.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dkanada/frost/issues/70#issuecomment-343991365

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by xphnx** [comment]
<quote> I definitely want to include icons for certain other apps like the Lineage camera, FastHub, or Magisk, but I am still not sure where to draw the line for support</quote>
I agree. For me a FLOSS license is enought. What about 2 appfilter parts? A main part with fdroid scraped lines and another one with other floss apps lines, manually updated. 

<quote>What you think about modi the turtl APP</quote>
I can grant permissions inthe gitlab repo to who  wants, for modifiying Turl in the direction needed. I have not the skills for writing that code.

**Comment by dkanada** [comment]
@xphnx I was actually planning on adding the code to the icon pack so users wouldn't need a separate app. I will probably be using a lot of the code from turtl for this. I am unsure about using two appfilter files because there is no easy way to combine them from the code, it would have to be done with a script. I ran into a similar issue when I was trying to figure out a way to keep the icon packs updated.

@beli3ver alright, PHP will work fine.

**Comment by xphnx** [comment]
Any progress with this?

**Comment by dkanada** [comment]
None so far, I spent winter break making a Chip8 emulator instead. I am adding it to the play store soon, just have a few tasks to finish first. This is still on my radar though, it's so annoying to add icons manually.

**Comment by xphnx** [comment]
I stay tuned.

**Comment by dkanada** [comment]
Okay, I am working on the database design and have a couple of questions for all of you.

1. Can you think of examples where one icon would be used by two different packages? Maybe something like FastHub and FastHub-Libre. Do you think this would be a good idea?

2. Do you think it would be a good idea to include "default" icons for some apps? I am talking about the generic icons being used if no icon is found for a certain app. For example, if the icon pack doesn't have an icon for Google Calendar, the generic calendar icon would be used instead.

3. Should the service allow for custom icon filenames or use a default schema? So FastHub would have to be named fasthub.svg every time. Not sure if this would make things easier or harder, I am on the fence about this right now.

4. Should we modify Turtl or just include the code in the icon pack. I am leaning towards the icon pack since it will not be that much code in the first place, an users wouldn't have to download a different app.

Lastly, does anyone have experience with frontend work and have any free time to help with the project? I can use whatever works best but help would be appreciated. I will make a repository if anyone can contribute code. I have worked with databases before but good CSS is a mystery to me.

**Comment by dkanada** [comment]
Here is a basic outline of what the website would do. It would have a list of every icon in the database. Icon pack creaters would check a box for every icon they have and the server would generate an appfilter.xml for every icon in that pack.

Positives:
- It would include every version of the class name in the database automatically, so no more work trying to update the component name for each app on every project
- Could add support for icons that wouldn't have been there before, in the case of "defaults" or several apps being able to use one icon

Negatives:
- Have to run a server, that costs money and adds complexity to the icon pack projects we have plus requires problem solving on this project to get it working
- Still requires quite a bit of work to get icons added to an icon pack, doesn't reduce effort that much
- I personally hate adding server components to something as simple as an icon pack, maybe this could be accomplished with scripts somehow instead of adding so much complexity to the project

**Comment by ikocevski** [comment]
I personally hate adding server components to something as simple as an icon pack, maybe this could be accomplished with scripts somehow instead of adding so much complexity to the project

This.

**Comment by xphnx** [comment]
I think the icon packs have lost a bit of interest from users, and it is likely that the adaptive icons will definitely end with the need to customize icons in the future ...
For my part, I have the icon pack quite unattended.
My opinion is that mounting a server would involve too much complexity

**Comment by beli3ver** [comment]
Same here.

**Comment by dkanada** [comment]
Sounds good, no worries. Closing this issue then. I will see if I can think of a better way to organize the app filter xml though, I hate how difficult the process is for adding the component names.
