### ISSUE TITLE
F-Droid icon...

### ISSUE THREAD

**Issue by ghost** [dkanada/frost#71]
I just noticed that the F-Droid icon is a little transparent. Not on my computer so I thought I'd make an issue before I forget about this.

**Comment by dkanada** [comment]
I just checked the file and there isn't any transparency on the current commit, maybe it was fixed at some point?

**Comment by dkanada** [comment]
Just checked the image you linked in GIMP, the icon is indeed transparent. I also checked the svg file for the F-Droid icon. It looked fine so I recreated the jpg files in the app. Hopefully that fixes it.

**Comment by dkanada** [comment]
Is this fixed in the latest update on F-Droid?

**Comment by ikocevski** [comment]
Mark as WONTFIX and move on 😉

**Comment by dkanada** [comment]
No way, this makes no sense and I refuse to let it go unsolved! The icon itself has no transparency so it shouldn't be opaque in the launcher.

**Comment by fredddii** [comment]
Issue tested and is no longer present. Closing this ticket.

![screenshot_20181027-170727_openlauncher](https://user-images.githubusercontent.com/15217150/47605756-e7e6f080-da0a-11e8-98e8-bc585af73584.png)

**Comment by dkanada** [comment]
@fredddii thanks for the update, wonder what the original issue was.
