### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by t-augusto** [dkanada/frost#74]
Some of these are my phone's stock apps and as such I think there are icons already for them(but not mapped currently, since it's an obscure/unknown phone), others are some apps of my region.
Thanks a bunch for the great work!
[20171231_112629.zip](https://github.com/dkanada/frost/files/1595562/20171231_112629.zip)

**Comment by Donnnno** [comment]
Here's a list with the icons and the ones that are in the icon pack already:
- ~~andOTP~~
- ~~AntennaPod~~
- Camera
- Clock
- ~~Dir~~
- DroidShows
- Eleven
- Evie
- iFood
- Itau light
- Lite
- ~~Netflix~~
- Nubank
- Ox Drive
- ~~Pocket~~
- ~~QR Scanner~~
- ~~Slack~~
- SulAmerica Saude
- Twitch
- Uber
- Weather

**Comment by nonnominandus** [comment]
I created all the missing icons, because I like to finish old work.
![preview7](https://user-images.githubusercontent.com/25853274/81819780-0c90b380-9530-11ea-99c2-95e714663b31.png)

**Comment by nonnominandus** [comment]
@dkanada As I lately drew the last icons this issue can be closed.
