### ISSUE TITLE
Icon request: Yalp Store

### ISSUE THREAD

**Issue by fredddii** [dkanada/frost#78]
Application info:
https://f-droid.org/en/packages/com.github.yeriomin.yalpstore/

[20180129_114204.zip](https://github.com/dkanada/frost/files/1675528/20180129_114204.zip)

**Comment by dkanada** [comment]
I think this should already be fixed in the next update, I will leave the issue open until then just to make sure though. F-Droid might take a while to pick up the release, last I read they were about 130 new builds behind schedule.

**Comment by dkanada** [comment]
Was this fixed with the latest update on F-Droid?
