### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by armabon** [dkanada/frost#82]
[20180423_093731.zip](https://github.com/dkanada/frost/files/1937054/20180423_093731.zip)

Icon request for Silence and andOTP apps.

Thanks for your awesome work !

**Comment by crishaddad** [comment]
Silence is included in PR #125. 
andOTP is currently included as of v1.4.4. 

i.e. this issue can be closed once #125 is merged

**Comment by dkanada** [comment]
just merged #125 so this issue is good to go :)
