### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by rharvest** [dkanada/frost#83]
[20180425_055732.zip](https://github.com/dkanada/frost/files/1948383/20180425_055732.zip)

androidVNC, busybox, CoolReader, DroidShows, OSMonitor, privacyFriendlyCodeScanner, sensorssandbox, Simple last.fm Scrobbler

**Comment by crishaddad** [comment]
Busybox was included in PR #121 and merged in 1.4.4

**Comment by h-bruch** [comment]
androidVNC, privacyFriendlyCodeScanner, Simple last.fm Scrobbler are also present as of 1.6.1. 

Osmonitor is not longer maintained.
