### ISSUE TITLE
How to make 48px icons not blurry

### ISSUE THREAD

**Issue by Swedneck** [dkanada/frost#86]
I made an icon and now i'm trying to convert it to 48 px to submit it, but i'm not sure how you manage to create 48px icons that aren't blurry?

**Comment by dkanada** [comment]
Is the icon in svg format? What software did you use to make it?

**Comment by Swedneck** [comment]
Making it in inkscape, i just don't see how a 48x48px icon can possibly be sharp..

**Comment by dkanada** [comment]
Since it's a vector the original size doesn't really matter, the shapes can be moved to within 1/100 of a pixel in Inkscape. When I run a script to convert the vector to an image it will upscale the vector to a larger size so it isn't blurry.

**Comment by Swedneck** [comment]
Oh so you export them to a higher resolution? Why have the svg be 48x48 then?

**Comment by dkanada** [comment]
Just so they're all a standard size, makes it easier to edit them in the future. If you import one shape into another and they aren't the same size you have to scale one before anything else can be done.
