### ISSUE TITLE
The future?

### ISSUE THREAD

**Issue by ghost** [dkanada/frost#93]
I'm definitely moving away from GitHub for good. I don't like being under MSFT's umbrella and besides I always thought of switching because it was a proprietary platform anyway. I heven't been active lately here but this is the project I contributed  to the most so I want to say thank you for all the good work done, it's been nice hanging out here. I'll delete my account and [I'll move to GitLab](https://gitlab.com/ikocevski). I'm not going to judge you if you want to stay and I wish you well going forward. Thanks again and goodbye (from here).

**Comment by dkanada** [comment]
I will probably move to GitLab eventually, for now I will be here though. See you on GitLab!
