### ISSUE TITLE
Move to gitlab?

### ISSUE THREAD

**Issue by swedneck** [dkanada/frost#94]
I've previously contributed here but since deleted my account due to github being bought by microsoft (remade it to be able to open issues), since many others have done the same it might be good to migrate this repo to gitlab? Gitlab lets you import repos with just a few clicks so it shouldn't be too difficult i hope.

**Comment by dkanada** [comment]
I will probably do so at some point in the future to support GitLab, but for now I will stay on GitHub. If Microsoft does a single thing I don't like with GitHub I will immediately move, but for now they seem to be doing nothing with it.
